---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-view-kazukt-github-io-v1-markdownview
  failurePolicy: Fail
  name: mmarkdownview.kb.io
  rules:
  - apiGroups:
    - view.kazukt.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - markdownviews
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-view-kazukt-github-io-v1-markdownview
  failurePolicy: Fail
  name: vmarkdownview.kb.io
  rules:
  - apiGroups:
    - view.kazukt.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - markdownviews
  sideEffects: None
